{
  "openapi": "3.0.0",
  "info": {
    "title": "Ramp developer",
    "version": "1.0",
    "description": "Ramp's developer API makes it easier for companies to programmatically set up and manage their card program.\n\nIt provides the ability to automate card issuing and the ability to integrate features like reporting with other software platforms.",
    "termsOfService": "https://ramp.com/developer-agreement"
  },
  "servers": [
    {
      "url": "https://api.ramp.com/developer/v1"
    }
  ],
  "paths": {
    "/users/{id}": {
      "get": {
        "summary": "Get User Info by User ID",
        "tags": [
          "User"
        ],
        "operationId": "get-users-userId",
        "description": "Retrieve the information of the user with the matching user ID.",
        "security": [
          {
            "OAuth 2.0": [
              "users:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Modify Existing User",
        "operationId": "patch-users-id",
        "description": "Modify information about a user.",
        "security": [
          {
            "OAuth 2.0": [
              "users:write"
            ]
          }
        ],
        "tags": [
          "User"
        ]
      },
      "delete": {
        "summary": "Suspend a user",
        "operationId": "delete-users-id",
        "description": "Suspends a user. Does not delete the user's cards. Currently this action is not reversible.",
        "security": [
          {
            "OAuth 2.0": [
              "users:write"
            ]
          }
        ],
        "tags": [
          "User"
        ]
      }
    },
    "/transactions": {
      "get": {
        "summary": "List transactions",
        "tags": [
          "Transaction"
        ],
        "operationId": "get-transaction",
        "description": "Retrieves all transactions for the business. This endpoint supports filtering and ordering. NOTE: only one ordering param is supported.",
        "security": [
          {
            "OAuth 2.0": [
              "transactions:read"
            ]
          }
        ]
      }
    },
    "/locations": {
      "get": {
        "summary": "List locations",
        "tags": [
          "Location"
        ],
        "operationId": "get-location",
        "description": "Retrieves all locations for your business.",
        "security": [
          {
            "OAuth 2.0": [
              "locations:read"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create new location",
        "operationId": "post-location",
        "description": "Creates a new location for the business. ",
        "tags": [
          "Location"
        ],
        "security": [
          {
            "OAuth 2.0": [
              "locations:write"
            ]
          }
        ]
      }
    },
    "/users": {
      "get": {
        "summary": "List users",
        "tags": [
          "User"
        ],
        "operationId": "get-users",
        "description": "Retrieve all users of the business. ",
        "security": [
          {
            "OAuth 2.0": [
              "users:read"
            ]
          }
        ]
      }
    },
    "/locations/{id}": {
      "get": {
        "summary": "GET a location",
        "tags": [
          "Location"
        ],
        "operationId": "get-locations-location_id",
        "description": "Retrieve a specific location. ",
        "security": [
          {
            "OAuth 2.0": [
              "locations:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update location",
        "operationId": "patch-locations-location_id",
        "description": "Modifies a specific location. ",
        "tags": [
          "Location"
        ],
        "security": [
          {
            "OAuth 2.0": [
              "locations:write"
            ]
          }
        ]
      }
    },
    "/departments": {
      "get": {
        "summary": "List departments",
        "tags": [
          "Department"
        ],
        "operationId": "get-departments",
        "description": "Retrieve all departments.",
        "security": [
          {
            "OAuth 2.0": [
              "departments:read"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create department",
        "operationId": "post-departments",
        "description": "Create a new department.",
        "tags": [
          "Department"
        ],
        "security": [
          {
            "OAuth 2.0": [
              "departments:write"
            ]
          }
        ]
      }
    },
    "/departments/{id}": {
      "get": {
        "summary": "GET a department",
        "tags": [
          "Department"
        ],
        "operationId": "get-department-department_id",
        "description": "Retrieve a single department.",
        "security": [
          {
            "OAuth 2.0": [
              "departments:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update department",
        "operationId": "patch-department-department_id",
        "description": "Modify a department. ",
        "tags": [
          "Department"
        ],
        "security": [
          {
            "OAuth 2.0": [
              "departments:write"
            ]
          }
        ]
      }
    },
    "/cards": {
      "get": {
        "summary": "List cards",
        "tags": [
          "Card"
        ],
        "operationId": "get-cards",
        "description": "Retrieve all cards.",
        "security": [
          {
            "OAuth 2.0": [
              "cards:read"
            ]
          }
        ]
      }
    },
    "/cards/{id}": {
      "get": {
        "summary": "GET a card",
        "tags": [
          "Card"
        ],
        "operationId": "get-cards-card_id",
        "description": "Retrieve a single card.",
        "security": [
          {
            "OAuth 2.0": [
              "cards:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update card",
        "operationId": "patch-resources-cards-card_id",
        "description": "Update card details",
        "tags": [
          "Card"
        ],
        "security": [
          {
            "OAuth 2.0": [
              "cards:write"
            ]
          }
        ]
      }
    },
    "/custom-id-provider": {
      "get": {
        "summary": "GET the Custom ID provider linked to the current OAuth token",
        "operationId": "get-custom_id-custom-id-provider",
        "tags": [
          "Custom ID"
        ],
        "security": [
          {
            "OAuth 2.0": []
          }
        ]
      },
      "post": {
        "summary": "Create a Custom ID provider",
        "operationId": "postcustom-id-provider",
        "description": "",
        "tags": [
          "Custom ID"
        ]
      }
    },
    "/custom-id-provider/application-link": {
      "post": {
        "summary": "",
        "operationId": "post-custom-id-provider-application-link",
        "description": "Register an access token with a custom ID provider",
        "tags": [
          "Custom ID"
        ],
        "security": [
          {
            "OAuth 2.0": []
          }
        ]
      }
    },
    "/business": {
      "get": {
        "summary": "GET business metadata",
        "tags": [
          "Business"
        ],
        "operationId": "get-resources-business",
        "description": "Gets metadata about a business.",
        "security": [
          {
            "OAuth 2.0": [
              "business:read"
            ]
          }
        ]
      }
    },
    "/transactions/{id}": {
      "get": {
        "summary": "GET a transaction",
        "tags": [
          "Transaction"
        ],
        "operationId": "get-resources-transactions-transaction_id",
        "description": "",
        "security": [
          {
            "OAuth 2.0": [
              "transactions:read"
            ]
          }
        ]
      }
    },
    "/cards/deferred/physical": {
      "post": {
        "summary": "Create a physical card",
        "operationId": "post-resources-card-physical",
        "tags": [
          "Card"
        ],
        "description": "",
        "security": [
          {
            "OAuth 2.0": [
              "cards:write"
            ]
          }
        ]
      }
    },
    "/cards/deferred/virtual": {
      "post": {
        "summary": "Create a virtual card",
        "operationId": "post-resources-card-virtual",
        "tags": [
          "Card"
        ],
        "description": "",
        "security": [
          {
            "OAuth 2.0": [
              "cards:write"
            ]
          }
        ]
      }
    },
    "/token": {
      "post": {
        "summary": "Get OAuth2 token",
        "operationId": "post-token",
        "tags": [
          "Auth"
        ],
        "description": "Returns an access token for accessing endpoints. There are three methods to get an access token:\n* \"authorization\\_code\": Authorization Code Grant method, used for retrieving an access token for the first time\n* \"refresh\\_token\": Refresh Token method, used for retrieving subsequent access tokens using the refresh token provided from authorization code grant\n* \"client\\_credentials\": Client Credentials method, allows direct retrieval of access tokens with only c[...]"
      }
    },
    "/business/balance": {
      "get": {
        "summary": "GET current info about a business",
        "tags": [
          "Business"
        ],
        "operationId": "get-resources-business-current",
        "description": "Gets current information about a business.",
        "security": [
          {
            "OAuth 2.0": [
              "business:read"
            ]
          }
        ]
      }
    },
    "/cards/{id}/deferred/termination": {
      "post": {
        "summary": "Delete a card",
        "operationId": "post-resources-cards-card_id-termination",
        "tags": [
          "Card"
        ],
        "description": "Terminates a card permanently.",
        "security": [
          {
            "OAuth 2.0": [
              "cards:write"
            ]
          }
        ]
      }
    },
    "/cards/{id}/deferred/suspension": {
      "post": {
        "summary": "Suspend a card",
        "operationId": "post-resources-cards-card_id-suspension",
        "tags": [
          "Card"
        ],
        "description": "Suspends a card so that it is locked from use. The suspension is revertable.",
        "security": [
          {
            "OAuth 2.0": [
              "cards:write"
            ]
          }
        ]
      }
    },
    "/cards/{id}/deferred/unsuspension": {
      "post": {
        "summary": "Removes a card's suspension",
        "operationId": "post-resources-cards-card_id-unsuspension",
        "tags": [
          "Card"
        ],
        "description": "Removes a card's suspension so that it may be used again.",
        "security": [
          {
            "OAuth 2.0": [
              "cards:write"
            ]
          }
        ]
      }
    },
    "/custom-id-provider/{entity_type}/{custom_id}/ramp-id": {
      "get": {
        "summary": "Convert custom id to ramp id",
        "tags": [
          "Custom ID"
        ],
        "operationId": "get-entity_type-custom_id-ramp-id",
        "description": "",
        "security": [
          {
            "OAuth 2.0": []
          }
        ]
      }
    },
    "/custom-id-provider/{entity_type}/{ramp_id}/custom-id": {
      "get": {
        "summary": "Convert ramp id to custom id",
        "tags": [
          "Custom ID"
        ],
        "operationId": "get-entity_type-ramp_id-custom-id",
        "security": [
          {
            "OAuth 2.0": []
          }
        ]
      }
    },
    "/cards/deferred/status/{id}": {
      "get": {
        "summary": "Get status of a deferred card task",
        "tags": [
          "Card"
        ],
        "operationId": "get-resources-cards-deferred-id",
        "description": "Gets status of a deferred task for cards",
        "security": [
          {
            "OAuth 2.0": [
              "cards:write"
            ]
          }
        ]
      }
    },
    "/card-programs": {
      "get": {
        "summary": "List card programs",
        "tags": [
          "Card Program"
        ],
        "operationId": "get-card_programs",
        "description": "Retrieve all card programs.",
        "security": [
          {
            "OAuth 2.0": [
              "card_programs:read"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create a card program",
        "operationId": "post-resources-card_program",
        "tags": [
          "Card Program"
        ],
        "description": "",
        "security": [
          {
            "OAuth 2.0": [
              "card_programs:write"
            ]
          }
        ]
      }
    },
    "/card-programs/{id}": {
      "get": {
        "summary": "GET a card program",
        "tags": [
          "Card Program"
        ],
        "operationId": "get-card_programs-card_program_id",
        "description": "Retrieve a single card program.",
        "security": [
          {
            "OAuth 2.0": [
              "card_programs:read"
            ]
          }
        ]
      }
    },
    "/users/deferred": {
      "post": {
        "summary": "Invite a new user",
        "operationId": "post-users-deferred",
        "description": "Creates an invite for the user to accept. Also optionally sets department, location, and manager.",
        "security": [
          {
            "OAuth 2.0": [
              "users:write"
            ]
          }
        ],
        "tags": [
          "User"
        ]
      }
    },
    "/users/deferred/status/{id}": {
      "get": {
        "summary": "Get status of a deferred user task",
        "tags": [
          "User"
        ],
        "operationId": "get-users-deferred-status-id",
        "description": "Gets status of a deferred task for users",
        "security": [
          {
            "OAuth 2.0": [
              "users:write"
            ]
          }
        ]
      }
    },
    "/receipts": {
      "get": {
        "summary": "List receipts",
        "tags": [
          "Receipt"
        ],
        "operationId": "get-receipts",
        "description": "Returns description of all receipts of a business.",
        "security": [
          {
            "OAuth 2.0": [
              "receipts:read"
            ]
          }
        ]
      }
    },
    "/receipts/{id}": {
      "get": {
        "summary": "Get details for one receipt",
        "tags": [
          "Receipt"
        ],
        "operationId": "get-receipts-receipt_id",
        "description": "",
        "security": [
          {
            "OAuth 2.0": [
              "receipts:read"
            ]
          }
        ]
      }
    },
    "/reimbursements": {
      "get": {
        "summary": "List Reimbursements",
        "tags": [
          "Reimbursement"
        ],
        "operationId": "get-reimbursements",
        "security": [
          {
            "OAuth 2.0": [
              "reimbursements:read"
            ]
          }
        ]
      }
    },
    "/reimbursements/{id}": {
      "get": {
        "summary": "Get details for one reimbursement",
        "tags": [
          "Reimbursement"
        ],
        "operationId": "get-reimbursements-id",
        "security": [
          {
            "OAuth 2.0": [
              "reimbursements:read"
            ]
          }
        ]
      }
    },
    "/custom-id-provider/{entity_type}/custom-id-link": {
      "post": {
        "summary": "Create custom id link",
        "operationId": "post-custom-id-provider-entity-type-custom-id-link",
        "security": [
          {
            "OAuth 2.0": []
          }
        ],
        "description": "Create a mapping between custom\\_id and ramp\\_id under the namespace specified by entity\\_type.",
        "tags": [
          "Custom Id"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth 2.0": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "scopes": {
              "transactions:read": "",
              "cards:read": "",
              "cards:write": "",
              "card_programs:read": "",
              "card_programs:write": "",
              "users:read": "",
              "users:write": "",
              "locations:read": "",
              "locations:write": "",
              "departments:read": "",
              "departments:write": "",
              "business:read": "",
              "receipts:read": "",
              "reimbursements:read": ""
            },
            "tokenUrl": "https://api.ramp.com/v1/public/customer/token",
            "refreshUrl": "https://api.ramp.com/v1/public/customer/token",
            "authorizationUrl": "https://app.ramp.com/v1/authorize"
          },
          "clientCredentials": {
            "tokenUrl": "",
            "refreshUrl": "",
            "scopes": {}
          }
        }
      }
    }
  }
}
